# Generated by Django 3.0.2 on 2020-01-21 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthorsModels',
            new_name='Author',
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Author'},
        ),
    ]
