# Generated by Django 3.0.2 on 2020-01-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_articles_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateField(),
        ),
    ]
