# Generated by Django 3.0.2 on 2020-01-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_category_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='pass_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
